import { createClient } from "@deepgram/sdk";
import fs from "fs";
import FormData from "form-data";
import fetch from "node-fetch";
import open from "open";

const transcribeFile = async () => {
  try {
    const deepgram = createClient(process.env.DEEPGRAM_API_KEY);

    const { result, error } = await deepgram.listen.prerecorded.transcribeFile(
      fs.readFileSync("hello.m4a"),
      {
        model: "nova-2",
        smart_format: true,
      }
    );

    if (error) throw error;

    const transcriptFilePath = "hello.txt";
    const transcript = result.channels[0].alternatives[0].transcript;
    fs.writeFileSync(transcriptFilePath, transcript);

    const apiUrl = "http://localhost:55000/transcriptions?async=false";
    const formData = new FormData();
    formData.append("audio", fs.createReadStream("hello.m4a"));
    formData.append("transcript", fs.createReadStream(transcriptFilePath));

    const apiResponse = await fetch(apiUrl, {
      method: "POST",
      body: formData,
    });

    if (!apiResponse.ok) {
      throw new Error(`API request failed: ${apiResponse.statusText}`);
    }

    const apiResult = await apiResponse.json();

    const outputFilePath = "output.txt";
    const { transcript: alignedTranscript, words } = apiResult;
    const phonemes = words.map((word) => ({
      word: word.alignedWord,
      phones: word.phones,
    }));

    const outputContent = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Transcription and Phoneme Analysis</title>
        <style>
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f4f4f9;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 0;
          }
          header {
            background-color: #283593;
            color: white;
            padding: 20px;
            text-align: center;
            font-size: 2em;
            font-weight: bold;
          }
          .container {
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
          }
          .section {
            margin-bottom: 30px;
          }
          h2 {
            color: #3f51b5;
            font-size: 1.5em;
          }
          pre {
            background-color: #eeeeee;
            padding: 15px;
            border-radius: 5px;
            font-size: 1.1em;
            white-space: pre-wrap;
            word-wrap: break-word;
          }
          .phoneme-list {
            list-style-type: none;
            padding-left: 0;
          }
          .phoneme-list li {
            background-color: #f1f1f1;
            margin-bottom: 10px;
            padding: 10px;
            border-radius: 5px;
          }
          .phoneme-list li span {
            font-weight: bold;
            color: #1976d2;
          }
          footer {
            background-color: #283593;
            color: white;
            text-align: center;
            padding: 10px;
            font-size: 0.9em;
          }
          .button {
            display: inline-block;
            padding: 10px 20px;
            margin-top: 20px;
            background-color: #3f51b5;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            font-weight: bold;
            text-align: center;
          }
          .button:hover {
            background-color: #303f9f;
          }
        </style>
      </head>
      <body>
        <header>Deepgram Transcription and Phoneme Analysis</header>
        <div class="container">
          <section class="section">
            <h2>Transcript</h2>
            <p><strong>Transcription Text:</strong></p>
            <pre>${alignedTranscript}</pre>
          </section>
          <section class="section">
            <h2>Phonemes</h2>
            <p><strong>Phoneme Analysis:</strong></p>
            <ul class="phoneme-list">
              ${phonemes.map(word => `
                <li>
                  <span>Word:</span> ${word.word}<br>
                  <span>Phonemes:</span> ${word.phones.map(phone => phone.phone).join(', ')}
                </li>
              `).join('')}
            </ul>
          </section>
          <a href="#" class="button" onclick="window.location.reload();">Reload Data</a>
        </div>
        <footer>Generated by Deepgram API - 2024</footer>
      </body>
      </html>
    `;

    fs.writeFileSync(outputFilePath, outputContent);

    open(outputFilePath);
  } catch (error) {
    console.error("Error:", error);
  }
};

transcribeFile();